from database.dal.dal_car import CarDAL
from database.dal.dal_car_condition import CarConditionDAL
from database.dal.dal_car_generation import CarGenerationDAL
from database.dal.dal_car_mark import CarMarkDAL
from database.dal.dal_car_type import CarTypeDAL
from database.dal.dal_car_colour import CarColourDAL
from database.dal.dal_car_engine import CarEngineDAL
from database.dal.dal_car_gearbox import CarGearboxDAL
from database.dal.dal_car_generation_period import CarGenerationPeriodDAL
from database.dal.dal_car_performance_characteristic import CarPerformanceCharacteristicDAL
from database.dal.dal_car_model import CarModelDAL
from database.dal.dal_car_photo import CarPhotoDAL
